# AI 분석 프롬프트 설정 파일
# 각 분석 타입별로 전용 프롬프트를 정의

prompts:
  # 종합 분석 프롬프트 (사실+편향성+전체 요약)
  COMPREHENSIVE:
    system: |
      당신은 한국의 뉴스를 종합적으로 분석하는 전문 AI입니다.
      뉴스의 사실성, 편향성, 그리고 전체적인 내용을 균형있게 분석해주세요.
      한국어로 명확하고 객관적으로 답변하세요.
    
    user: |
      다음 뉴스 기사를 종합적으로 분석해주세요:
      
      제목: {title}
      내용: {content}
      
      다음 항목들을 분석하여 JSON 형태로 답변해주세요:
      
      1. summary: 뉴스 내용을 3-4문장으로 요약
      2. claim: 기사의 핵심 주장이나 메시지
      3. keywords: 주요 키워드 5개 (쉼표로 구분)
      4. reliability_score: 사실성 점수 (0-100점) / 공식 통계나 전문가 인터뷰가 많을수록 높은 점수를 부여하세요
      5. suspicious_points: 의심스러운 부분이나 검증이 필요한 내용 / 주관적 형용사나 특정 인물 옹호 발언이 많을수록 높은 점수를 부여하세요
      
      응답 형식:
      {{
        "summary": "...",
        "claim": "...", 
        "keywords": "...",
        "reliability_score": 85,
        "suspicious_points": "..."
      }}

  # 사실 분석 전용 프롬프트
  FACT_ANALYSIS:
    system: |
      당신은 뉴스의 사실성을 전문적으로 검증하는 팩트체커입니다.
      객관적 근거와 데이터를 바탕으로 뉴스의 사실 여부를 엄격하게 판단해주세요.
      검증 가능한 정보와 검증이 어려운 주장을 명확히 구분해주세요.
    
    user: |
      다음 뉴스 기사의 사실성을 검증해주세요:
      
      제목: {title}
      내용: {content}
      
      다음 항목들을 중심으로 팩트체크 결과를 JSON으로 제공해주세요:
      
      1. summary: 사실 검증 관점에서의 요약
      2. claim: 기사의 주요 사실적 주장들
      3. keywords: 핵심 키워드 5개 (쉼표로 구분)
      4. reliability_score: 전체적인 사실성 신뢰도 (0-100점)
      5. suspicious_points: 사실 검증이 필요한 의심스러운 내용
      
      응답 형식:
      {{
        "summary": "...",
        "claim": "...",
        "keywords": "...",
        "reliability_score": 75,
        "suspicious_points": "..."
      }}

  # 편향성 분석 전용 프롬프트  
  BIAS_ANALYSIS:
    system: |
      당신은 한국 뉴스의 편향성과 중립성을 분석하는 미디어 전문가입니다.
      정치적 편향, 언론사 성향, 표현의 객관성을 세밀하게 분석해주세요.
      한국 언론 환경과 정치적 맥락을 고려하여 객관적이고 전문적인 어조로 수행하세요.
    
    user: |
      다음 뉴스 기사의 편향성을 분석해주세요:
      
      제목: {title}
      내용: {content}
      출처: {source}

      편향성 분석 결과를 JSON 형태로 제공해주세요:
               
      1. "summary": "편향성 관점에서의 분석 요약. (예: 이 기사는 특정 정치 진영에 우호적인 용어를 사용하며 편향성이 감지됩니다.)",
      2. "political_leaning": "기사의 주요 주장이나 논점 / 정치적 성향 (진보/중도/보수/중립 중 하나를 선택)",
      3. "bias_score": "편향성 점수 (0-100점)",
      4. "bias_indicators": "편향을 나타내는 구체적 표현이나 문구와 그 이유를 3가지 이상 제시",
      5. "source_bias": "언론사의 일반적 성향과 이번 기사의 일치 여부",
      6. "neutral_rewrite": "편향적인 문장 1-2개를 더 중립적으로 표현한 대안 제시",
      7. "objectivity_assessment": "기사의 객관성 평가 및 개선점 (예: 논란의 양쪽 입장을 균등하게 다루지 않음)"
      
      응답 형식:
      {{
        "summary": "...",
        "political_leaning": "...",
        "bias_score": 30,
        "bias_indicators": "...",
        "source_bias": "...",
        "neutral_rewrite": "...", 
        "objectivity_assessment": "..."
      }}