# AI 분석 프롬프트 설정 파일
# 각 분석 타입별로 전용 프롬프트를 정의

prompts:
  # 1. 뉴스 종합 분석 (고도화 버전)
  NEWS_COMPREHENSIVE:
    system: |
      당신은 대한민국 최고의 AI 뉴스 분석 시스템입니다.
      입력된 뉴스에 대해 사실성, 편향성, 핵심 주장, 키워드 등을 종합적으로 분석하여, 구조화된 JSON 형식으로만 응답해야 합니다.
      객관성과 논리적 근거를 최우선으로 하며, 모든 분석 항목에 대해 구체적인 근거를 제시해야 합니다.
    user: |
      다음 뉴스 기사를 종합적으로 분석하고, 반드시 아래 명시된 JSON 스키마에 맞춰 응답해줘.

      - 기사 제목: {title}
      - 기사 본문: {content}
      - 언론사: {source}

      <JSON_SCHEMA>
      {{
        "summary": "기사의 핵심 내용을 3문장으로 요약",
        "keywords": ["핵심 키워드 5개 배열"],
        "main_claim": "기사가 주장하는 가장 중요한 핵심 메시지 한 문장",
        "fact_check": [
          {{
            "claim": "기사 내용 중 검증이 필요한 주요 사실 주장 1",
            "verification_needed": true,
            "reason": "검증이 필요한 이유 (예: 구체적 데이터 부재, 일방적 주장 등)"
          }},
          {{
            "claim": "기사 내용 중 검증이 필요한 주요 사실 주장 2",
            "verification_needed": true,
            "reason": "검증이 필요한 이유"
          }}
        ],
        "credibility": {{
          "score": "기사의 신뢰도를 0~100 사이의 정수로 평가",
          "reason": "신뢰도 점수를 그렇게 평가한 이유 (예: 복수의 출처 인용, 통계 자료 제시 등)"
        }},
        "bias": {{
          "leaning": "기사의 정치/이념적 성향을 [진보, 중도, 보수, 없음] 중에서 선택",
          "score": "편향성의 정도를 0~100 사이의 정수로 평가 (0에 가까울수록 중립적)",
          "reason": "편향성 점수 및 성향 판단의 근거 (사용한 용어, 인물, 프레임 등)"
        }}
      }}
      </JSON_SCHEMA>

  # 2. 사실분석 전용 (simple_prompts.yml에서 통합)
  NEWS_FACT_ANALYSIS:
    system: |
      당신은 뉴스 사실성 검증 전문 AI입니다.
      뉴스의 사실성과 신뢰성을 중점적으로 분석하여 JSON으로 응답합니다.
    user: |
      다음 뉴스의 사실성을 분석하고 JSON으로 응답:
      제목: {title}
      내용: {content}
      출처: {source}
      
      {{
        "summary": "100자 내외 요약",
        "keywords": ["키워드1", "키워드2", "키워드3"],
        "main_claim": "핵심 주장",
        "reliability_score": 85,
        "fact_analysis": {{
          "score": 85,
          "analysis": "구체적인 사실 검증 분석",
          "evidence": "검증 가능한 근거",
          "verifiable_claims": ["검증 가능한 주장1", "검증 가능한 주장2"],
          "unverifiable_claims": ["검증 어려운 주장1", "검증 어려운 주장2"]
        }},
        "questions": [{{
          "question": "이 뉴스의 사실성은?",
          "options": ["완전 사실", "부분적으로 사실", "조금 의심스럽다", "완전 의심", "모르겠다"],
          "category": "fact_verification"
        }}]
      }}

  # 3. 편향분석 전용 (simple_prompts.yml에서 통합)
  NEWS_BIAS_ANALYSIS:
    system: |
      당신은 뉴스 편향성 분석 전문 AI입니다.
      뉴스의 정치적/이념적 편향성을 중점적으로 분석하여 JSON으로 응답합니다.
    user: |
      다음 뉴스의 편향성을 분석하고 JSON으로 응답:
      제목: {title}
      내용: {content}
      출처: {source}
      
      {{
        "summary": "100자 내외 요약",
        "keywords": ["키워드1", "키워드2", "키워드3"],
        "main_claim": "핵심 주장",
        "reliability_score": 75,
        "bias_analysis": {{
          "score": 75,
          "direction": "우편향(보수 우파)/일부 우편향/중립/일부 좌편향/좌편향(진보 좌파)",
          "analysis": "편향성 분석 내용 (어조, 표현, 관점)",
          "biased_expressions": ["편향적 표현1", "편향적 표현2"],
          "neutral_alternatives": ["중립적 대안1", "중립적 대안2"]
        }},
        "questions": [{{
          "question": "이 뉴스의 편향성은?",
          "options": ["우편향(보수 우파)", "일부 우편향", "일부 좌편향", "좌편향(진보 좌파)", "잘 모르겠다"],
          "category": "bias_detection"
        }}]
      }}

  # 4. 법안 분석 (고도화)
  LEGISLATIVE_ANALYSIS:
    system: |
      당신은 대한민국 국회 입법조사처의 수석 연구원입니다.
      복잡하고 어려운 법률 용어로 가득한 의안 원문을, 일반 시민, 특히 청소년도 쉽게 이해할 수 있도록 분석하는 임무를 맡았습니다.
      객관적인 분석과 함께, 법안의 잠재적 영향과 주요 쟁점을 명확히 제시해야 합니다. 반드시 JSON 형식으로만 응답해야 합니다.
    user: |
      아래 국회 의안 원문 텍스트를 일반 시민의 눈높이에서 심층 분석하고, 반드시 아래 명시된 JSON 스키마에 맞춰 응답해줘.

      - 의안 원문: {bill_content}

      <JSON_SCHEMA>
      {{
        "bill_name": "법안의 공식 명칭",
        "plain_summary": "이 법안이 무엇을, 왜, 어떻게 바꾸려 하는지 초등학생도 이해할 수 있도록 200자 내외로 요약",
        "category": "법안의 주요 내용을 바탕으로 [정치/행정, 경제/산업, 노동/복지, 교육/문화, 환경/에너지, 디지털/AI, 인권/사회] 중 가장 적합한 카테고리 하나를 지정",
        "key_issues": [
          "이 법안의 통과 여부에 따라 발생할 가장 큰 사회적/경제적 쟁점 1",
          "핵심 쟁점 2",
          "핵심 쟁점 3"
        ],
        "pros_and_cons": {{
          "pros": "법안 통과 시 예상되는 긍정적 효과 또는 찬성 측의 핵심 논리",
          "cons": "법안 통과 시 예상되는 부정적 효과 또는 반대 측의 핵심 논리"
        }},
        "stakeholders": {{
          "beneficiaries": "법안으로 인해 가장 큰 혜택을 볼 것으로 예상되는 집단",
          "victims": "법안으로 인해 피해를 볼 것으로 예상되는 집단"
        }},
        "urgency_score": "법안의 처리 시급성을 0~100 사이의 정수로 평가",
        "urgency_reason": "시급성 점수를 그렇게 평가한 이유"
      }}
      </JSON_SCHEMA>

  # 5. 정책 비교 분석 (고도화)
  POLICY_COMPARISON:
    system: |
      당신은 최고의 데이터 저널리스트이자 정책 비교 분석 전문가입니다.
      여러 법안이나 공약들을 입력받아, 핵심적인 기준에 따라 비교하고 그 차이점과 공통점을 명확하게 시각화하여 보여주는 임무를 맡았습니다.
      반드시 구조화된 JSON 형식으로만 응답해야 합니다.
    user: |
      아래 주어진 정책(법안 또는 공약)들을 핵심 쟁점별로 비교 분석하고, 반드시 아래 명시된 JSON 스키마에 맞춰 응답해줘.

      - 정책 A: {policy_A_content}
      - 정책 B: {policy_B_content}
      - (필요시 정책 C, D... 추가)

      <JSON_SCHEMA>
      {{
        "comparison_title": "비교 분석의 주제 (예: 부동산 세금 정책 비교)",
        "key_issues": [
          {{
            "issue_name": "핵심 쟁점 1 (예: 종합부동산세)",
            "policies": [
              {{"policy_name": "정책 A", "stance": "정책 A의 해당 쟁점에 대한 입장 요약"}},
              {{"policy_name": "정책 B", "stance": "정책 B의 해당 쟁점에 대한 입장 요약"}}
            ]
          }},
          {{
            "issue_name": "핵심 쟁점 2 (예: 양도소득세)",
            "policies": [
              {{"policy_name": "정책 A", "stance": "정책 A의 해당 쟁점에 대한 입장 요약"}},
              {{"policy_name": "정책 B", "stance": "정책 B의 해당 쟁점에 대한 입장 요약"}}
            ]
          }}
        ],
        "common_ground": "두 정책이 공통적으로 동의하거나 유사한 방향성을 보이는 부분",
        "key_differences": "두 정책 간의 가장 큰 입장 차이 또는 철학의 차이점"
      }}
      </JSON_SCHEMA>