spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/factlab}
    username: ${SPRING_DATASOURCE_USERNAME:factlab_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

    # mail:
    #   host: smtp.gmail.com
    #   port: 587
    #   username: your-email@gmail.com
    #   password: your-app-password
    #   properties:
    #     mail:
    #       smtp:
    #         auth: true
    #         starttls:
    #           enable: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  application:
    name: factlab-backend
  
  security:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: factlab-secret-key-for-jwt-token-generation-please-change-in-production
  expiration: 3600000  # 1시간 

logging:
  level:
    com.factlab.admin: DEBUG
    com.factlab.admin.service.AdminAuthService: DEBUG
    org.springframework.security: DEBUG
    root: INFO