spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/factlab}
    username: ${SPRING_DATASOURCE_USERNAME:factlab_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

    # mail:
    #   host: smtp.gmail.com
    #   port: 587
    #   username: your-email@gmail.com
    #   password: your-app-password
    #   properties:
    #     mail:
    #       smtp:
    #         auth: true
    #         starttls:
    #           enable: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  application:
    name: factlab-backend
  
  security:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: factlab-secret-key-for-jwt-token-generation-please-change-in-production
  expiration: 3600000  # 1시간

# 소셜 로그인 OAuth 설정
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID:your_google_client_id}
    client-secret: ${GOOGLE_CLIENT_SECRET:your_google_client_secret}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}
  naver:
    client-id: ${NAVER_CLIENT_ID:your_naver_client_id}
    client-secret: ${NAVER_CLIENT_SECRET:your_naver_client_secret}
    redirect-uri: ${NAVER_REDIRECT_URI:http://localhost:8080/api/auth/naver/callback}
  kakao:
    client-id: ${KAKAO_CLIENT_ID:your_kakao_client_id}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}

# 앱 설정
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

# 외부 API 설정
api:
  assembly:
    key: ${ASSEMBLY_API_KEY:your_assembly_api_key_here}
    base-url: https://open.assembly.go.kr/portal/openapi 

logging:
  level:
    com.factlab.admin: DEBUG
    com.factlab.admin.service.AdminAuthService: DEBUG
    org.springframework.security: DEBUG
    root: INFO