spring:
  # --- Default (local, non-Docker) Profile ---
  datasource:
    url: jdbc:postgresql://localhost:5432/factlab # 로컬 개발용 DB
    username: factlab
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  application:
    name: factlab-backend
  
  security:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: "dev"
  # --- Development (Docker) Profile ---
  datasource:
    url: jdbc:postgresql://database:5432/factlab # Docker dev용 DB
    username: factlab
    password: password123

---
spring:
  config:
    activate:
      on-profile: "prod"
  # --- Production (Docker) Profile ---
  datasource:
    url: jdbc:postgresql://database:5432/factlab # Docker prod용 DB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:factlab-secret-key-for-jwt-token-generation-please-change-in-production}
  expiration: 3600000  # 1시간

# 소셜 로그인 OAuth 설정
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI:http://localhost:8080/api/auth/naver/callback}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}

# 앱 설정
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

# 외부 API 설정
api:
  assembly:
    key: ${ASSEMBLY_API_KEY:your_assembly_api_key_here}
    base-url: https://open.assembly.go.kr/portal/openapi 

logging:
  level:
    com.factlab: DEBUG
    org.springframework.security: DEBUG
    root: INFO
